# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Physics-based Deep Learning
author: N. Thuerey, P. Holl, M. Mueller, P. Schnell, F. Trost, K. Um
logo: resources/logo.jpg
copyright: "2021,2022"
only_build_toc_files: true

launch_buttons:
  colab_url: https://colab.research.google.com
  binderhub_url: "" # not supported for now

execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/tum-pbs/pbdl-book/ # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: "favicon.ico"
